###
GET http://localhost:9000/api/arts HTTP/1.1 
Content-Type: application/json

{} 

###
POST http://localhost:9000/api/favorites HTTP/1.1
Content-Type: application/json

{}

###
GET http://localhost:9000/api/favorites/2 HTTP/1.1

{}